from tests.helpers.module_loaders import load_local_speech_attribute


def test_text_config_exposes_expected_measure_keys():
    speech_attribute = load_local_speech_attribute()
    measures = speech_attribute.get_config(speech_attribute.__file__, "text.json")

    for key in (
        "file_length",
        "speech_minutes",
        "speech_words",
        "turn_minutes",
        "turn_words",
        "word_pause",
        "turn_pause",
        "speaker_label",
    ):
        assert key in measures


def test_empty_payload_uses_configured_output_schema():
    speech_attribute = load_local_speech_attribute()
    measures = speech_attribute.get_config(speech_attribute.__file__, "text.json")

    word_df, turn_df, summary_df = speech_attribute.speech_characteristics({}, language="en")

    assert list(word_df.columns) == [
        measures["word_pause"],
        measures["num_syllables"],
        measures["part_of_speech"],
        measures["first_person"],
        measures["verb_tense"],
        measures["word_coherence"],
        measures["word_coherence_5"],
        measures["word_coherence_10"],
        measures["word_coherence_variability_2"],
        measures["word_coherence_variability_3"],
        measures["word_coherence_variability_4"],
        measures["word_coherence_variability_5"],
        measures["word_coherence_variability_6"],
        measures["word_coherence_variability_7"],
        measures["word_coherence_variability_8"],
        measures["word_coherence_variability_9"],
        measures["word_coherence_variability_10"],
    ]
    assert list(turn_df.columns) == [
        measures["turn_pause"],
        measures["turn_minutes"],
        measures["turn_words"],
        measures["word_rate"],
        measures["syllable_rate"],
        measures["speech_percentage"],
        measures["pause_meandur"],
        measures["pause_var"],
        measures["pos"],
        measures["neg"],
        measures["neu"],
        measures["compound"],
        measures["pos_vader"],
        measures["neg_vader"],
        measures["neu_vader"],
        measures["compound_vader"],
        measures["speech_mattr_5"],
        measures["speech_mattr_10"],
        measures["speech_mattr_25"],
        measures["speech_mattr_50"],
        measures["speech_mattr_100"],
        measures["first_person_percentage"],
        measures["first_person_sentiment_positive"],
        measures["first_person_sentiment_negative"],
        measures["word_repeat_percentage"],
        measures["phrase_repeat_percentage"],
        measures["sentence_tangeniality1"],
        measures["sentence_tangeniality2"],
        measures["turn_to_turn_tangeniality"],
        measures["turn_to_previous_speaker_turn_similarity"],
        measures["perplexity"],
        measures["perplexity_5"],
            measures["perplexity_11"],
            measures["perplexity_15"],
            measures["interrupt_flag"],
        ]
    assert list(summary_df.columns) == [
        measures["file_length"],
        measures["speech_minutes"],
        measures["speech_words"],
        measures["word_rate"],
        measures["syllable_rate"],
        measures["word_pause_mean"],
        measures["word_pause_var"],
        measures["speech_percentage"],
        measures["pos"],
        measures["neg"],
        measures["neu"],
        measures["compound"],
        measures["pos_vader"],
        measures["neg_vader"],
        measures["neu_vader"],
        measures["compound_vader"],
        measures["speech_mattr_5"],
        measures["speech_mattr_10"],
        measures["speech_mattr_25"],
        measures["speech_mattr_50"],
        measures["speech_mattr_100"],
        measures["first_person_percentage"],
        measures["prop_verb_past"],
        measures["prop_function_words"],
        measures["first_person_sentiment_positive"],
        measures["first_person_sentiment_negative"],
        measures["first_person_sentiment_overall"],
        measures["word_repeat_percentage"],
        measures["phrase_repeat_percentage"],
        measures["word_coherence_mean"],
        measures["word_coherence_var"],
        measures["word_coherence_5_mean"],
        measures["word_coherence_5_var"],
        measures["word_coherence_10_mean"],
        measures["word_coherence_10_var"],
        measures["word_coherence_variability_2_mean"],
        measures["word_coherence_variability_2_var"],
        measures["word_coherence_variability_3_mean"],
        measures["word_coherence_variability_3_var"],
        measures["word_coherence_variability_4_mean"],
        measures["word_coherence_variability_4_var"],
        measures["word_coherence_variability_5_mean"],
        measures["word_coherence_variability_5_var"],
        measures["word_coherence_variability_6_mean"],
        measures["word_coherence_variability_6_var"],
        measures["word_coherence_variability_7_mean"],
        measures["word_coherence_variability_7_var"],
        measures["word_coherence_variability_8_mean"],
        measures["word_coherence_variability_8_var"],
        measures["word_coherence_variability_9_mean"],
        measures["word_coherence_variability_9_var"],
        measures["word_coherence_variability_10_mean"],
        measures["word_coherence_variability_10_var"],
        measures["num_turns"],
        measures["num_one_word_turns"],
        measures["turn_minutes_mean"],
        measures["turn_words_mean"],
        measures["turn_pause_mean"],
        measures["speaker_percentage"],
        measures["sentence_tangeniality1_mean"],
        measures["sentence_tangeniality1_var"],
        measures["sentence_tangeniality2_mean"],
        measures["sentence_tangeniality2_var"],
        measures["turn_to_turn_tangeniality_mean"],
        measures["turn_to_turn_tangeniality_var"],
        measures["turn_to_turn_tangeniality_slope"],
        measures["turn_to_previous_speaker_turn_similarity_mean"],
        measures["turn_to_previous_speaker_turn_similarity_var"],
        measures["turn_to_previous_speaker_turn_similarity_slope"],
        measures["perplexity_mean"],
        measures["perplexity_var"],
        measures["perplexity_5_mean"],
        measures["perplexity_5_var"],
        measures["perplexity_11_mean"],
        measures["perplexity_11_var"],
        measures["perplexity_15_mean"],
        measures["perplexity_15_var"],
        measures["num_interrupts"],
    ]
