STRICT_SUMMARY_INVARIANTS = (
    "file_length",
    "speech_length_minutes",
    "speech_percentage",
    "speaker_percentage",
    "num_turns",
)

STRONG_CROSS_LANGUAGE_SUMMARY_COLUMNS = (
    "sentiment_pos",
    "sentiment_neg",
    "sentiment_neu",
    "sentiment_overall",
    "first_person_sentiment_positive",
    "first_person_sentiment_negative",
    "first_person_sentiment_overall",
    "word_coherence_mean",
    "word_coherence_5_mean",
    "word_coherence_10_mean",
)

MODERATE_CROSS_LANGUAGE_SUMMARY_COLUMNS = (
    "mattr_5",
    "mattr_10",
    "mattr_25",
    "mattr_50",
    "mattr_100",
    "sentiment_vader_pos",
    "sentiment_vader_neg",
    "sentiment_vader_neu",
    "sentiment_vader_overall",
    "prop_verb_past",
    "prop_function_words",
)

REPORT_ONLY_CROSS_LANGUAGE_SUMMARY_COLUMNS = (
    "semantic_perplexity_mean",
    "semantic_perplexity_var",
    "semantic_perplexity_5_mean",
    "semantic_perplexity_5_var",
    "semantic_perplexity_11_mean",
    "semantic_perplexity_11_var",
    "semantic_perplexity_15_mean",
    "semantic_perplexity_15_var",
    "first_order_sentence_tangeniality_mean",
    "first_order_sentence_tangeniality_var",
    "second_order_sentence_tangeniality_mean",
    "second_order_sentence_tangeniality_var",
    "turn_to_turn_tangeniality_mean",
    "turn_to_turn_tangeniality_var",
    "turn_to_turn_tangeniality_slope",
)

LANGUAGE_DEPENDENT_SUMMARY_COLUMNS = (
    "speech_length_words",
    "words_per_min",
    "syllables_per_min",
    "mattr_5",
    "mattr_10",
    "mattr_25",
    "mattr_50",
    "mattr_100",
)

FEATURE_GROUPS = ("pause", "repetition", "coherence", "sentiment", "first_person")

REQUIRED_OUTPUT_COLUMNS = {
    "words": (
        "pre_word_pause",
        "num_syllables",
        "part_of_speech",
        "first_person",
        "verb_tense",
        "word_coherence",
        "word_coherence_5",
        "word_coherence_10",
    ),
    "turns": (
        "pre_turn_pause",
        "turn_length_minutes",
        "turn_length_words",
        "words_per_min",
        "syllables_per_min",
        "speech_percentage",
        "mean_pause_length",
        "pause_variability",
    ),
    "summary": STRICT_SUMMARY_INVARIANTS,
}

PAUSE_REPETITION_SUMMARY_COLUMNS = STRICT_SUMMARY_INVARIANTS + (
    "speech_length_words",
    "words_per_min",
    "syllables_per_min",
    "mean_pre_word_pause",
    "mean_pause_variability",
    "mean_turn_length_minutes",
    "mean_turn_length_words",
    "mean_pre_turn_pause",
    "num_one_word_turns",
    "word_repeat_percentage",
    "phrase_repeat_percentage",
)

SENTIMENT_FIRST_PERSON_SUMMARY_COLUMNS = (
    "file_length",
    "speaker_percentage",
    "sentiment_pos",
    "sentiment_neg",
    "sentiment_neu",
    "sentiment_overall",
    "sentiment_vader_pos",
    "sentiment_vader_neg",
    "sentiment_vader_neu",
    "sentiment_vader_overall",
    "mattr_5",
    "mattr_10",
    "mattr_25",
    "mattr_50",
    "mattr_100",
    "first_person_percentage",
    "prop_verb_past",
    "prop_function_words",
    "first_person_sentiment_positive",
    "first_person_sentiment_negative",
    "first_person_sentiment_overall",
    "first_person_sentiment_positive_vader",
    "first_person_sentiment_negative_vader",
    "first_person_sentiment_overall_vader",
)

COHERENCE_SUMMARY_COLUMNS = (
    "file_length",
    "speaker_percentage",
    "word_coherence_mean",
    "word_coherence_var",
    "word_coherence_5_mean",
    "word_coherence_5_var",
    "word_coherence_10_mean",
    "word_coherence_10_var",
    "word_coherence_variability_2_mean",
    "word_coherence_variability_2_var",
    "word_coherence_variability_3_mean",
    "word_coherence_variability_3_var",
    "word_coherence_variability_4_mean",
    "word_coherence_variability_4_var",
    "word_coherence_variability_5_mean",
    "word_coherence_variability_5_var",
    "word_coherence_variability_6_mean",
    "word_coherence_variability_6_var",
    "word_coherence_variability_7_mean",
    "word_coherence_variability_7_var",
    "word_coherence_variability_8_mean",
    "word_coherence_variability_8_var",
    "word_coherence_variability_9_mean",
    "word_coherence_variability_9_var",
    "word_coherence_variability_10_mean",
    "word_coherence_variability_10_var",
)
