STRICT_FLOAT_TOLERANCE = 1e-6
STRONG_FLOAT_TOLERANCE = 0.15
FIRST_PERSON_SENTIMENT_TOLERANCE = 5.0
MODERATE_FLOAT_TOLERANCE = 0.15
DEFAULT_DF_RTOL = 1e-6
DEFAULT_DF_ATOL = 1e-5
MODEL_DF_RTOL = 1e-1
MODEL_DF_ATOL = 2e-2
